# Generated by Django 5.2.7 on 2025-10-10 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='plant',
            name='aps_urn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='plant',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='MqttConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(help_text='ex: 74.63.254.231', max_length=255)),
                ('port', models.IntegerField(default=1883)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('client_id', models.CharField(blank=True, max_length=64, null=True)),
                ('topics', models.JSONField(default=list, help_text='[{topic,label}, ...]')),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt', to='core.plant')),
            ],
        ),
    ]
