# Generated by Django 5.2.7 on 2025-10-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_plant_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='grafana_uid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
