# Generated by Django 5.2.7 on 2025-10-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_plant_tags'),
    ]

    operations = [
    ]
