# Generated by Django 5.2.7 on 2025-10-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_slugs'),
    ]

    operations = [
    ]
