# Generated by Django 5.2.7 on 2025-10-20 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mqttdatapoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('ts', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.DeleteModel(
            name='MqttDataPoint',
        ),
        migrations.AddField(
            model_name='plant',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plant'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['plant', 'metric', 'ts'], name='core_measur_plant_i_1b295b_idx'),
        ),
    ]
