# Generated by Django 5.2.7 on 2025-10-20 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_measurement_delete_mqttdatapoint_plant_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={},
        ),
        migrations.AlterField(
            model_name='measurement',
            name='metric',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='core.plant'),
        ),
    ]
