# Generated by Django 5.2.6 on 2025-10-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_measurement_options_alter_measurement_metric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbid', models.PositiveIntegerField(help_text='dbId do elemento no APS Viewer', verbose_name='dbId (Viewer)')),
                ('key', models.CharField(blank=True, help_text='Ex.: ENERGY.Power (opcional se usar tópico + campo)', max_length=120, verbose_name='Chave em payload.values')),
                ('topic', models.CharField(blank=True, help_text='Ex.: tele/xisto_A399CE/SENSOR (opcional se usar apenas "key")', max_length=200, verbose_name='Tópico MQTT')),
                ('field_path', models.CharField(blank=True, help_text='Ex.: ENERGY.Power (usado junto com "Tópico MQTT")', max_length=200, verbose_name='Campo dentro do payload')),
                ('label_template', models.CharField(default='{value}', help_text='Use {value} para o valor (ex.: {value} W, {value}&#176;C)', max_length=120, verbose_name='Template do rótulo')),
                ('css', models.CharField(default='fas fa-map-marker-alt', help_text='Ex.: fas fa-bolt, fas fa-thermometer-half (Font Awesome)', max_length=120, verbose_name='Classe CSS do ícone')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='core.plant')),
            ],
            options={
                'ordering': ['plant', 'sort_order', 'id'],
            },
        ),
    ]
